name: elisha_ej_williams
description: "Official app for EJ Williams - Actor, Voice Artist, and Rising Star"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_messaging: ^14.6.9
  firebase_remote_config: ^4.3.8
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.6.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/home_background.jpg
    - assets/splash.jpg
    - assets/siganture.png
    - assets/signature_text.png
    - assets/about.png
    - assets/social.png
    - assets/videos.png
    - assets/messages.png
    - assets/share.png
    - assets/feature_background.jpg
    - assets/feature_header.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"