name: elisha_ej_williams
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_messaging: ^14.6.9
  firebase_remote_config: ^4.3.8
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.6.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/home_background.jpg
    - assets/splash.jpg
    - assets/siganture.png
    - assets/signature_text.png
    - assets/about.png
    - assets/social.png
    - assets/videos.png
    - assets/messages.png
    - assets/share.png
    - assets/feature_background.jpg
    - assets/feature_header.png