// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcBWnVuShYah2pvHkRCHpqTwoQ6NEU8sI',
    appId: '1:806443614801:web:a105891a6674960af56e70',
    messagingSenderId: '806443614801',
    projectId: 'elisha-ej-williams',
    authDomain: 'elisha-ej-williams.firebaseapp.com',
    storageBucket: 'elisha-ej-williams.firebasestorage.app',
    measurementId: 'G-8ZCEK0D0GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXSVdykYVUG6l3TWjnusfGNRRxViqnYY',
    appId: '1:806443614801:android:b57c3852e676fc12f56e70',
    messagingSenderId: '806443614801',
    projectId: 'elisha-ej-williams',
    storageBucket: 'elisha-ej-williams.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr_iHhOMAUuBysXATUIXvfBfCfsNDEGHU',
    appId: '1:806443614801:ios:70c03d26eb2f5536f56e70',
    messagingSenderId: '806443614801',
    projectId: 'elisha-ej-williams',
    storageBucket: 'elisha-ej-williams.firebasestorage.app',
    iosBundleId: 'app.ios.elisha-ej-williams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr_iHhOMAUuBysXATUIXvfBfCfsNDEGHU',
    appId: '1:806443614801:ios:70c03d26eb2f5536f56e70',
    messagingSenderId: '806443614801',
    projectId: 'elisha-ej-williams',
    storageBucket: 'elisha-ej-williams.firebasestorage.app',
    iosBundleId: 'app.ios.elisha-ej-williams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcBWnVuShYah2pvHkRCHpqTwoQ6NEU8sI',
    appId: '1:806443614801:web:3f25f48a8f6f64fbf56e70',
    messagingSenderId: '806443614801',
    projectId: 'elisha-ej-williams',
    authDomain: 'elisha-ej-williams.firebaseapp.com',
    storageBucket: 'elisha-ej-williams.firebasestorage.app',
    measurementId: 'G-C3XNXGD07X',
  );
}
